coverage:
  # Commit status https://docs.codecov.io/docs/commit-status are used
  # to block PR based on coverage threshold.
  status:
    project:
      default:
        target: 80
        threshold: 1%
    patch:
      # Disable the coverage threshold of the patch, so that PRs are
      # only failing because of overall project coverage threshold.
      # See https://docs.codecov.io/docs/commit-status#disabling-a-status.
      default: false
comment:
  # Update existing comment or create new if deleted.
  behavior: default
ignore:
  - "docs"
  - "hack"
  - "templates"
  - "vendor"
