run:
  timeout: 5m

linters:
  enable:
    - prealloc
    - unconvert
    - unparam
  disable:
    - errcheck

issues:
  exclude-rules:
    - path: test # Excludes /test, *_test.go etc.
      linters:
        - unparam
